name: Secret Scan

on:
  push:
  pull_request:
  schedule:
    - cron: "45 2 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository history
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@466da5b0bb161144f6afca9afe5d57975828c410 # v3.90.8
        with:
          version: 3.90.8
          head: HEAD
